# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://sbussmann.github.io/fastai_part2_lessons/"

git_url = "https://github.com/sbussmann/fastai_part2_lessons/tree/master/"

def custom_doc_links(name): return None
